import { useQueries, useQuery } from '@tanstack/react-query'
import { CarFront, IndianRupee, ClipboardCheck, Star, Users } from 'lucide-react'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { api } from '../../services/api'; import { useAuthStore } from '../../store/authStore'; import { StatCard } from '../../components/ui/StatCard'; import { PageState } from '../../components/ui/PageState'
export function DashboardPage() {
  const user=useAuthStore(s=>s.user); const admin=user?.role==='ADMIN'; const analytics=useQuery({queryKey:['analytics-dashboard'],queryFn:()=>api.get('/analytics/dashboard'),enabled:admin}); const trends=useQuery({queryKey:['analytics-trends'],queryFn:()=>api.get('/analytics/trends?days=30'),enabled:admin}); const vendor=useQueries({queries:[{queryKey:['vendor-vehicles'],queryFn:()=>api.get('/vehicles/vendor/me'),enabled:!admin},{queryKey:['vendor-bookings'],queryFn:()=>api.get('/bookings/vendor/me'),enabled:!admin}]}); const loading=admin?analytics.isLoading:vendor.some(q=>q.isLoading); const data=analytics.data||{}; const vehicles=vendor[0]?.data||[]; const bookings=vendor[1]?.data||[]
  const stats=admin?[[Users,'Active users',data.users||0,'Across the platform','mint'],[CarFront,'Active vehicles',data.vehicles||0,'Approved inventory','blue'],[ClipboardCheck,'Bookings',data.bookings||0,`${data.activeBookings||0} active now`,'amber'],[IndianRupee,'Captured revenue',`₹${Number(data.revenue||0).toLocaleString('en-IN')}`,'All time','violet']]:[[CarFront,'My vehicles',vehicles.length,`${vehicles.filter(v=>v.isApproved).length} approved`,'mint'],[ClipboardCheck,'Bookings received',bookings.length,`${bookings.filter(b=>b.status==='ACTIVE').length} active`,'blue'],[IndianRupee,'Completed value',`₹${bookings.filter(b=>b.status==='COMPLETED').reduce((a,b)=>a+(b.pricing?.totalAmount||0),0).toLocaleString('en-IN')}`,'Completed rentals','amber'],[Star,'Fleet readiness',`${vehicles.length?Math.round(vehicles.filter(v=>v.isAvailable).length/vehicles.length*100):0}%`,'Vehicles available','violet']]
  return <><div className="page-heading"><div><span className="eyebrow">{new Date().toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long'})}</span><h1>Good day, {user?.name?.split(' ')[0]||'partner'}.</h1><p>Here is what is happening across your SmartRide workspace.</p></div></div><PageState loading={loading}><div className="stats-grid">{stats.map(([Icon,label,value,hint,tone])=><StatCard key={label} {...{icon:Icon,label,value,hint,tone}}/>)}</div><div className="dashboard-grid"><article className="panel panel--wide"><div className="panel__header"><div><span className="eyebrow">Performance</span><h3>{admin?'Booking activity':'Recent bookings'}</h3></div></div>{admin?<div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trends.data?.bookings||[]}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="_id"/><YAxis/><Tooltip/><Area type="monotone" dataKey="count" stroke="#146c5b" fill="#d7eee8" strokeWidth={3}/></AreaChart></ResponsiveContainer></div>:<div className="activity-list">{bookings.slice(0,5).map(b=><div key={b.id}><span className="activity-icon"><CarFront size={17}/></span><div><strong>{b.bookingCode}</strong><small>{b.vehicle?.brand} {b.vehicle?.model}</small></div><b>{b.status?.replaceAll('_',' ')}</b></div>)}</div>}</article><article className="panel"><div className="panel__header"><div><span className="eyebrow">Attention</span><h3>Quick summary</h3></div></div><div className="summary-ring"><strong>{admin?data.vendorsPending||0:vehicles.filter(v=>!v.isApproved).length}</strong><span>{admin?'vendors awaiting approval':'vehicles awaiting approval'}</span></div><p className="muted">Review pending items regularly to keep the marketplace moving smoothly.</p></article></div></PageState></>
}
